elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
pipeline_server:
  image:
    docker.uncharted.software/distil-pipeline-server:latest
  ports:
    - "45042:45042"
  environment:
    - PIPELINE_SERVER_RESULT_DIR=$PWD/datasets
    - PIPELINE_SEND_DELAY=2000
    - PIPELINE_NUM_UPDATES=3
    - PIPELINE_ERR_PERCENT=0.01
  volumes:
    - $PWD/datasets:$PWD/datasets
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres
nk_classification_rest:
  image:
    registry.datadrivendiscovery.org/j18_ta1eval/distil/simon:latest
  ports:
    - "5000:5000"
nk_ranking_rest:
  image:
    registry.datadrivendiscovery.org/j18_ta1eval/distil/punk_1:0.4
  ports:
    - "5001:5000"
