elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
pipeline_server:
  image:
    docker.uncharted.software/distil-pipeline-server:latest
  ports:
    - "50051:50051"
  environment:
    - PIPELINE_SERVER_RESULT_DIR=$PWD/datasets
    - PIPELINE_SEND_DELAY=0
  volumes:
    - $PWD/datasets:$PWD/datasets
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres

