elastic_redis:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
    - "6379:6379"
  user:
    elasticsearch
pipeline_server:
  image:
    docker.uncharted.software/distil-pipeline-server:latest
  ports:
    - "9500:9500"
  environment:
    - PIPELINE_SERVER_RESULT_DIR=$PWD/datasets
  volumes:
    - $PWD/datasets:$PWD/datasets
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  user:
    postgres
  command:
    ["-d postgres"]
