elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"

pipeline_server:
  image:
    docker.uncharted.software/distil-pipeline-server:latest
  ports:
    - "45042:45042"
  environment:
    - SOLUTION_SERVER_RESULT_DIR=$PWD/datasets
    - SOLUTION_SEND_DELAY=2000
    - SOLUTION_NUM_UPDATES=3
    - SOLUTION_MAX_SOLUTIONS=5
    - SOLUTION_ERR_PERCENT=0.1
  volumes:
    - $PWD/datasets:$PWD/datasets

postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres

runner:
  image:
    docker.uncharted.software/distil-pipeline-runner:latest
  ports:
    - "50051:50051"
  environment:
    - D3MOUTPUTDIR=$PWD/outputs
    - VERBOSE_PRIMITIVE_OUTPUT=1
    #- STATIC_RESOURCE_PATH=/static_resources
  volumes:
    - $PWD/datasets:/$PWD/datasets
    - $PWD/outputs:/$PWD/outputs
    #- $PWD/static_resources:/static_resources

resources:
  image:
    docker.uncharted.software/distil_res_server:latest
  ports:
    - "5440:5440"
