distil:
  image:
    docker.uncharted.software/distil:latest
#    entrypoint:
#      ta3_search
  ports:
    - "8080:8080"
  environment:
    # The SRI_TAG is the name of the SRI docker container as defined below
    - PIPELINE_COMPUTE_ENDPOINT=sri-tpot:45042
    - PG_HOST=postgres
    - ES_ENDPOINT=http://elastic:9200
    - PIPELINE_COMPUTE_TRACE=true
    - JSON_CONFIG_PATH=/datasets-sri/config/search_config.json
    - SKIP_INGEST=true
  volumes:
    - /datasets-sri/inputs:/inputs
    - /datasets-sri/outputs:/outputs
    - /datasets-sri/config/search_config.json:/datasets-sri/config/search_config.json
elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres
# SRI config here
sri-tpot:
  image:
    registry.datadrivendiscovery.org/j18_ta2eval/sri_tpot:stable
  ports:
    - 45042
  volumes:
    - /datasets-sri/inputs:/inputs
    - /datasets-sri/outputs:/outputs
    - /datasets-sri/config/search_config.json:/datasets-sri/config/search_config.json
  command:
    - ta2_server
    - /datasets-sri/config/search_config.json
