elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres
# SRI config here
sri-tpot:
  image:
    registry.datadrivendiscovery.org/j18_ta2eval/sri_tpot:stable
  ports:
    - 45042
  volumes:
    - /tmp/d3m/dataset:/tmp/d3m/dataset
    - $PWD/datasets/config.json:$PWD/datasets/config.json
  command:
    - ta2_server
    - $PWD/datasets/config.json
