elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres
qntfy_ta2:
  image: registry.datadrivendiscovery.org/uncharted_qntfy/ta3ta2_integration/qntfy_main:latest
  environment:
    - DEBUG=true
    - OUTPUT_DIR=/output
  volumes:
    - $PWD/datasets:/output
  ports:
    - "45042:45042"
