elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres
resources:
  image:
    docker.uncharted.software/distil_res_server:latest
  ports:
    - "5440:5440"
mitfl:
  image:
    registry.datadrivendiscovery.org/jkanter/mit-fl-ta2:stable
  ports:
    - "45042:45042"
  environment:
    - D3MTIMEOUT=60
    - D3MINPUTDIR=$PWD/outputs/temp
    - D3MOUTPUTDIR=$PWD/outputs/temp
    - D3MRUN=ta2ta3
    - D3MPORT=45042
  volumes:
    - $PWD/outputs/temp:$PWD/outputs/temp
