# ---------------------------------------------------------
# TA3 Kubernetes Pod Stub File
# ---------------------------------------------------------
## Specifications
# * Assumes a web service over ports 80 (http) and 443 https
# * Assumes a listening port 5001 to listen to TA2 signals
# * In this speicification, the ta3-main container has the web ports
# but one can have a separate container handle the web ports
# that is not the TA3-main container
---
# Web Port Service (perhaps Nginx)
apiVersion: v1
kind: Service
metadata:
  name: local-test-ta3-web
  labels:
    evalId:  local-test
    tier: ta3
spec:
  # NodePort type allows to expose service outside the cluster
  type: NodePort
  selector:
    evalId: local-test
    tier: ta3
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
---
# TA3 Service for taking requests from TA2
apiVersion: v1
kind: Service
metadata:
  name: local-test-ta3
  labels:
    evalId: local-test
    tier: ta3
spec:
  type: ClusterIP
  # There is a possibility of manually assigning an IP
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    evalId: local-test
    tier: ta3
---
# TA3 Pod
apiVersion: v1
kind: Pod
metadata:
  name: local-test-ta3
  labels:
    evalId: local-test
    main: "yes"
    tier: ta3
    ta3-main: "yes"
spec:
  restartPolicy: Never
  volumes:

    - name: shared-data
      emptyDir: {}

  containers:
  # TA3 container, entry point for evaluation
  - name: ta3-main
    image: docker.uncharted.software/distil:test
    imagePullPolicy: IfNotPresent
    command:
      - /bin/bash

    # web (perhaps nginx) ports
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
      - containerPort: 443
        name: https
        protocol: TCP
      # Additional Port for TA3 to listen to TA2 signals
      - containerPort: 5001
        protocol: TCP
    env:
      # environment variables passed to container
      - name: EVAL_ID
        value: local-test
      # Query TA2 Service with service name:
      # local-test-ta2:45042
      # Query TA3 Service with service name:
      # local-test-ta3:5001
      - name: TA2_PORT
        value: "45042"
      - name: TA3_PORT
        value: "5001"
      - name: PIPELINE_COMPUTE_ENDPOINT
        value: "localhost:45042"
      - name: PIPELINE_COMPUTE_TRACE
        value: "true"
    volumeMounts:

      - name: shared-data
        mountPath: /tmp/d3m/datasets


  # Postgres container - provides access to pre-loaded D3M data
  - name: distil-pg
    image: docker.uncharted.software/distil_dev_postgres:latest
    imagePullPolicy: IfNotPresent
    ports:
      - name: pg-port
        hostPort: 5432
        containerPort: 5432
    args: [-d postgres]

  # ElasticSearch container - provides indexing / search on pre-loaded D3M data
  - name: distil-es
    image: docker.uncharted.software/distil_dev_es:latest
    imagePullPolicy: IfNotPresent
    ports:
      - name: es-port
        containerPort: 9200
    env:
      - name: ES_JAVA_OPTS
        value: -Xmx512m -Xms512m


  # Stub ta2 container
  - name: ta2-main
    image: docker.uncharted.software/distil-pipeline-server:latest
    imagePullPolicy: IfNotPresent
    # environment variables passed to container
    env:
      # NIST eval id
      - name: EVAL_ID
        value: local-test
      - name: PIPELINE_SERVER_RESULT_DIR
        value: /tmp/d3m/datasets
    ports:
      # gRPC port
      - containerPort: 45042
        protocol: TCP
    volumeMounts:
      - name: shared-data
        mountPath: /tmp/d3m/datasets

