# Service exposing ta3-main
apiVersion: v1
kind: Service
metadata:
  name: distil-dev
  labels:
    evalId: distil-dev
spec:
  type: NodePort
  selector:
    evalId: distil-dev
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 443
---
# Pod Specification
apiVersion: v1
kind: Pod
metadata:
  name: distil
  labels:
    evalId: distil
    main: "yes"
spec:
  restartPolicy: Never
  volumes:
    # Shared volume mount to both containers
    - emptyDir: {}
      name: shared-vol
  containers:
    # TA3 container, entry point for evaluation
    - name: ta3-main
      image: docker.uncharted.software/distil:latest
      ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 443
      env:
        - name: EVAL_ID
          value: distil-dev
        - name: PIPELINE_DATA_DIR
          value: /shared_dir
      volumeMounts:
        - mountPath: /shared_dir
          name: shared-vol
          readOnly: false
    # Pipeline server container - acts as TA2 stand-in
    - name: ta2-main
      image: docker.uncharted.software/distil-pipeline-server:latest
      ports:
        - name: pipeline-port
          containerPort: 9500
      env:
        - name: EVAL_ID
          value: distil-dev
        - name: PIPELINE_SERVER_RESULT_DIR
          value: /shared_dir
    # Redis container - caches between web-client and ta3-main
    - name: redis
      image: redis:latest
      ports:
        - name: redis-port
          containerPort: 6379
      args: [redis-server, --save "", --appendonly no]
    # Postgres container - provides access to pre-loaded D3M data
    - name: distil-pg
      image: docker.uncharted.software/distil_dev_postgres:latest
      ports:
        - name: pg-port
          hostPort: 5432
          containerPort: 5432
      args: [-d postgres]
    # ElasticSearch container - provides indexing / search on pre-loaded D3M data
    - name: distil-es
      image: docker.uncharted.software/distil_dev_es:0.5.0
      ports:
        - name: es-port
          containerPort: 9200
      resources:
        limits:
          memory: "1000Mi"
        requests:
          memory: "500Mi"
  # For development debugging - not need when images are in D3M Gitlab repository
  imagePullSecrets:
    - name: uncharted-docker-repo
