# TA2 Service for taking requests from TA3
apiVersion: v1
kind: Service
metadata:
  name: distil-001-eval-ta2
  labels:
    evalId: distil-001-eval
    tier: ta2
spec:
  type: ClusterIP
  # There is a possibility of manually assigning an IP
  ports:
    - port: 45042
      targetPort: 45042
  selector:
    evalId: distil-001-eval
    tier: ta2
---
apiVersion: v1
kind: Pod
metadata:
  name: distil-001-eval-ta2
  labels:
    evalId: distil-001-eval
    ta2-main: "yes"
spec:
  restartPolicy: Never
  volumes:
    # - name: nfs-data
    #   persistentVolumeClaim:
    #     claimName: pvc-datasets
    # - name: nfs-output
    #   persistentVolumeClaim:
    #     claimName: pvc-rw
    # - name: nfs-resource_files
    #   persistentVolumeClaim:
    #     claimName: pvc-rw_temp
    # - name: nfs-resource_files

  containers:
    # -------------------------
    # Main TA2 Container
    # -------------------------
    - name: ta2-main
      image: docker.uncharted.software/distil-pipeline-server:latest
      imagePullPolicy: Always
      # environment variables passed to container
      env:
        # NIST eval id
        - name: EVAL_ID
          value: distil-001-eval

      ports:
        # gRPC port
        - containerPort: 45042
          protocol: TCP
      volumeMounts:
        # - name: nfs-data
        #   mountPath: /inputs
        #   subPath:
        #   readOnly: true
        # - name: nfs-output
        #   mountPath: /outputs
        #   subPath:
        # - name: nfs-resource_files
        #   mountPath: /shared_temp
