version: 2
jobs:
  build:
    docker:
      - image: docker.uncharted.software/distil-build:latest
        auth:
          username: $UNCHARTED_DOCKER_USERNAME
          password: $UNCHARTED_DOCKER_PW
        working_directory: /go/src/github.com/unchartedsoftware/distil
    steps:
      - checkout
      - run:
          name: build app binary
          command: /bin/sh -c "/build.sh"
      - run:
          name: run tests
          command: /bin/sh -c 'yarn test && go test $(glide novendor)'
