version: 2
jobs:
  build:
    docker:
      - image: docker.uncharted.software/distil-build:latest
    steps:
      - checkout
      - run:
          name: build app binary
          command: /bin/sh -c "/build.sh"
      