elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
ta2:
  image:
    primitive_test
  ports:
    - "45042:45042"
  environment:
    - DEBUG=true
    - OUTPUT_DIR=$PWD/../outputs
    - D3MTIMEOUT=60
    - D3MINPUTDIR=$PWD/../inputs
    - D3MOUTPUTDIR=$PWD/../outputs
    - D3MRUN=ta2ta3
    - D3MPORT=45042
  volumes:
    - $PWD/../outputs:$PWD/../outputs
    - $PWD/../inputs:$PWD/../inputs
  ports:
    - "45042:45042"
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres
resources:
  image:
    docker.uncharted.software/distil_res_server:latest
  ports:
    - "5440:5440"

